### ISSUE TITLE
cannot submit form or make post request?

### ISSUE THREAD

**Issue by jun1st** [turbolinks/turbolinks-ios#25]
I have a login form, and an app build with iOS adapter.

The form cannot be submitted when its inside a VisitableViewController,  

what I need to do to make it submittable? 

I've tried with a clean scaffold rails project, with rails 5 beta3,  and a model Book.  Below is the screenshot. The button is disabled, but nothing happens, and no post request is sent to server. 

<img width="378" alt="screen shot 2016-04-06 at 7 12 09 pm" src="https://cloud.githubusercontent.com/assets/140474/14314721/90142cfc-fc2b-11e5-992f-3e1aa09c1988.png">

**Comment by qrush** [comment]
@jun1st seeing any JS errors pop up? You can check via Safari with the Develop menu on if you're using the simulator (or via device- http://jeffreysambells.com/2012/09/22/ios-safari-web-inspector)

**Comment by jun1st** [comment]
@qrush No, didn't see any js errors, but xcode give this: 

> TurbolinksDemo[1471:78359] Snapshotting a view that has not been rendered results in an empty snapshot. Ensure your view has been rendered at least once before snapshotting or snapshot after screen updates

**Comment by jun1st** [comment]
After more playing around, it seems only GET request works,  all POST requests seems being handled someway, and requests doesn't reach server side.

**Comment by sstephenson** [comment]
Sorry for the trouble—there’s a bit of a blind spot in our documentation right now. You’ll want to make sure to submit all forms using XMLHttpRequest and [use the response to tell Turbolinks where to navigate afterwards](https://github.com/turbolinks/turbolinks#redirecting-after-a-form-submission). 

In a Rails app, I suggest using jquery-ujs in combination with the `data-remote` attribute to handle form submission. In your form actions, return a JavaScript response that calls `Turbolinks.visit(...)`.

Long-term, it makes sense for Turbolinks to handle form submission itself, but that’s something we didn’t get to for the first release.

The reason standard form submissions don’t work in iOS is because our [default navigation policy handler](https://github.com/turbolinks/turbolinks-ios/blob/b4937ea1bd3786c5552746ccc3cbf9676969c29b/Turbolinks/Session.swift#L273-L282) disables them. You’re welcome to try [implementing your own policy](https://github.com/turbolinks/turbolinks-ios#becoming-the-web-views-navigation-delegate), but I think you’ll find getting that right is a much more difficult task than just submitting forms over XHR :)

**Comment by jun1st** [comment]
Thanks for the quick response,  I'll go with jquery-ujs solution. :)
