### ISSUE TITLE
Disable bounce?

### ISSUE THREAD

**Issue by elsurudo** [turbolinks/turbolinks-ios#83]
Is there a sanctioned way to disable the "bounce" within `VisitableView`?

I've disabled "pull to refresh", but the view still gets "pulled down" farther than it should, unlike a native app.

I see that `VisitableView` has a `hiddenScrollView`, but unfortunately it is private. Perhaps disabling this functionality should be supported?

**Comment by zachwaugh** [comment]
Can you give me some more information about what you want to disable? You could disable the scroll view bounce by reaching into `webView.scrollView` and setting `bounces = false` and `alwaysBounceVertical = false`, but I'd recommend against that since it would make things feel very unnatural for iOS - https://developer.apple.com/reference/uikit/uiscrollview/1619420-bounces

**Comment by elsurudo** [comment]
Yeah, you're right. I decided to keep the bounce in there.
